/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InvoiceApplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Report extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        btnSalesReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablesalr = new javax.swing.JTable();
        txtCustomerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        button1.setLabel("Back");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        btnSalesReport.setText("Sale Report");
        btnSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesReportActionPerformed(evt);
            }
        });

        jTablesalr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No", "Date", "Customer Name", "Grand Total"
            }
        ));
        jScrollPane1.setViewportView(jTablesalr);

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        txtCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyTyped(evt);
            }
        });

        jLabel1.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalesReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtCustomerName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
InvoiceApplication invoicePanel = new InvoiceApplication();

//    getParent().removeAll();
//    getParent().add(invoicePanel);
//    getParent().revalidate();
//    getParent().repaint();        // TODO add your handling code here:
  //InvoiceApplication invoicePanel = new InvoiceApplication();

//    java.awt.Container parent = getParent();
//    if (parent != null) {
//        parent.removeAll();
//        parent.add(invoicePanel);
//        parent.revalidate();
//        parent.repaint();
//    } else {
//        JOptionPane.showMessageDialog(this, "⚠️ Unable to go back — parent container not found!");
//    }

   // open main invoice window
    InvoiceApplication mainWindow = new InvoiceApplication();
    mainWindow.setVisible(true);

    // close current report window
    java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
    }
    }//GEN-LAST:event_button1ActionPerformed

    private void btnSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesReportActionPerformed
loadSalesReport();   // TODO add your handling code here:
    }//GEN-LAST:event_btnSalesReportActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameKeyTyped

    private void txtCustomerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyReleased
         String name = txtCustomerName.getText().trim();
    fetchBillsByCustomerName(name);
    }//GEN-LAST:event_txtCustomerNameKeyReleased

   private void fetchBillsByCustomerName(String name) {
    try {
        Connection conn = DriverManager.getConnection("jdbc:h2:~/invoiceapp", "sa", "");

        // 🔽 ഇതാണ് പഴയ (തെറ്റായ) query
        // String sql = "SELECT invoice_no, date, customer_name, grand_total FROM invoices WHERE customer_name LIKE ? ORDER BY date DESC";

        // ✅ പുതിയ (ശരിയായ) query — ഇതാണ് ചേർക്കേണ്ടത് 👇
        String sql = "SELECT i.invoice_no, i.date, c.name AS customer_name, i.grand_total "
                   + "FROM invoices i "
                   + "JOIN customers c ON i.customer_id = c.id "
                   + "WHERE c.name LIKE ? "
                   + "ORDER BY i.date DESC";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + name + "%");

        ResultSet rs = ps.executeQuery();
        DefaultTableModel model = (DefaultTableModel) jTablesalr.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            String inv = rs.getString("invoice_no");
            String date = rs.getString("date");
            String cust = rs.getString("customer_name");
            double total = rs.getDouble("grand_total");
            model.addRow(new Object[]{inv, date, cust, total});
        }

        rs.close();
        ps.close();
        conn.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
    }
}


    
    

private void loadSalesReport() {
    try {
        // ✅ Database connection
        Connection conn = DriverManager.getConnection("jdbc:h2:~/invoiceapp", "sa", "");

        // ✅ SQL query (Java 8 compatible)
        String sql = "SELECT i.invoice_no, i.date, c.name AS customer_name, i.grand_total "
                   + "FROM invoices i "
                   + "JOIN customers c ON i.customer_id = c.id "
                   + "ORDER BY i.date DESC";

        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTablesalr.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            String inv = rs.getString("invoice_no");
            String date = rs.getString("date");
            String name = rs.getString("customer_name");
            double total = rs.getDouble("grand_total");

            model.addRow(new Object[]{inv, date, name, total});
        }

        rs.close();
        ps.close();
        conn.close();

        JOptionPane.showMessageDialog(this, "✅ Sales Report Loaded Successfully!");

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "❌ Error: " + ex.getMessage());
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalesReport;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablesalr;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables
}
